const GET_MY_TASKS_REQUEST = "TASKS_GET_MY_TASKS_REQUEST";
const GET_MY_TASKS_SUCCESS = "TASKS_GET_MY_TASKS_SUCCESS";
const GET_MY_TASKS_ERROR = "TASKS_GET_MY_TASKS_ERROR";
const GET_ADD_NEW_TASK_REQUEST = "TASKS_ADD_NEW_TASK_REQUEST";
const GET_ADD_NEW_TASK_SUCCESS = "TASKS_ADD_NEW_TASK_SUCCESS";
const GET_ADD_NEW_TASK_ERROR = "TASKS_ADD_NEW_TASK_ERROR";

export default {
  GET_MY_TASKS_REQUEST,
  GET_MY_TASKS_SUCCESS,
  GET_MY_TASKS_ERROR,
  GET_ADD_NEW_TASK_REQUEST,
  GET_ADD_NEW_TASK_SUCCESS,
  GET_ADD_NEW_TASK_ERROR
};
