const GET_MY_TASKS_REQUEST = "TASKS_GET_MY_TASKS_REQUEST";
const GET_MY_TASKS_SUCCESS = "TASKS_GET_MY_TASKS_SUCCESS";
const GET_MY_TASKS_ERROR = "TASKS_GET_MY_TASKS_ERROR";
const ADD_NEW_TASK_REQUEST = "TASKS_ADD_NEW_TASK_REQUEST";
const ADD_NEW_TASK_SUCCESS = "TASKS_ADD_NEW_TASK_SUCCESS";
const ADD_NEW_TASK_ERROR = "TASKS_ADD_NEW_TASK_ERROR";
const REMOVE_TASK_REQUEST = "TASKS_REMOVE_TASK_REQUEST";
const REMOVE_TASK_SUCCESS = "TASKS_REMOVE_TASK_SUCCESS";
const REMOVE_TASK_ERROR = "TASKS_REMOVE_TASK_ERROR";

export default {
  // MY TASKS
  GET_MY_TASKS_REQUEST,
  GET_MY_TASKS_SUCCESS,
  GET_MY_TASKS_ERROR,
  // ADD TASK
  ADD_NEW_TASK_REQUEST,
  ADD_NEW_TASK_SUCCESS,
  ADD_NEW_TASK_ERROR,
  // REMOVE TASK
  REMOVE_TASK_REQUEST,
  REMOVE_TASK_SUCCESS,
  REMOVE_TASK_ERROR
};
