const LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
const LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const LOGIN_ERROR = 'USER_LOGIN_ERROR'
const LOGOUT = 'USER_LOGOUT'

export default {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGOUT
}
